import SketchType from "../types";

interface InitData {
  page: SketchType.PageJSON;
  document: SketchType.DocumentJSON;
  meta: SketchType.MetaJSON;
}

export const INIT_DATA: InitData = {
  page: {
    _class: "page",
    do_objectID: "A869BA2A-E632-4C2D-924E-7883848BB266",
    booleanOperation: -1,
    isFixedToViewport: false,
    isFlippedHorizontal: false,
    isFlippedVertical: false,
    isLocked: false,
    isVisible: true,
    layerListExpandedType: 0,
    name: "Page 1",
    nameIsFixed: false,
    resizingConstraint: 63,
    resizingType: 0,
    rotation: 0,
    shouldBreakMaskChain: false,
    exportOptions: {
      _class: "exportOptions",
      includedLayerIds: [],
      layerOptions: 0,
      shouldTrim: false,
      exportFormats: [],
    },
    frame: {
      _class: "rect",
      constrainProportions: true,
      height: 0,
      width: 0,
      x: 0,
      y: 0,
    },
    clippingMaskMode: 0,
    hasClippingMask: false,
    style: {
      _class: "style",
      do_objectID: "8DDABED0-BE2D-46FC-895B-519F230FA08C",
      endMarkerType: 0,
      miterLimit: 10,
      startMarkerType: 0,
      windingRule: 1,
      blur: {
        _class: "blur",
        isEnabled: false,
        center: "{0.5, 0.5}",
        motionAngle: 0,
        radius: 10,
        saturation: 1,
        type: 0,
      },
      borderOptions: {
        _class: "borderOptions",
        isEnabled: true,
        dashPattern: [],
        lineCapStyle: 0,
        lineJoinStyle: 0,
      },
      borders: [],
      colorControls: {
        _class: "colorControls",
        isEnabled: false,
        brightness: 0,
        contrast: 1,
        hue: 0,
        saturation: 1,
      },
      contextSettings: {
        _class: "graphicsContextSettings",
        blendMode: 0,
        opacity: 1,
      },
      fills: [],
      innerShadows: [],
      shadows: [],
    },
    hasClickThrough: true,
    groupLayout: { _class: "MSImmutableFreeformGroupLayout" },
    layers: [
      {
        _class: "rectangle",
        do_objectID: "C52C7A8C-D98E-4877-B3F9-6D750033F861",
        booleanOperation: -1,
        isFixedToViewport: false,
        isFlippedHorizontal: false,
        isFlippedVertical: false,
        isLocked: false,
        isVisible: true,
        layerListExpandedType: 0,
        name: "Rectangle",
        nameIsFixed: false,
        resizingConstraint: 63,
        resizingType: 0,
        rotation: 0,
        shouldBreakMaskChain: false,
        exportOptions: {
          _class: "exportOptions",
          includedLayerIds: [],
          layerOptions: 0,
          shouldTrim: false,
          exportFormats: [],
        },
        frame: {
          _class: "rect",
          constrainProportions: false,
          height: 79,
          width: 113,
          x: 217,
          y: 135,
        },
        clippingMaskMode: 0,
        hasClippingMask: false,
        style: {
          _class: "style",
          do_objectID: "286B7F72-C269-4A11-9D7D-6FCE3020FC97",
          endMarkerType: 0,
          miterLimit: 10,
          startMarkerType: 0,
          windingRule: 1,
          blur: {
            _class: "blur",
            isEnabled: false,
            center: "{0.5, 0.5}",
            motionAngle: 0,
            radius: 10,
            saturation: 1,
            type: 0,
          },
          borderOptions: {
            _class: "borderOptions",
            isEnabled: true,
            dashPattern: [],
            lineCapStyle: 0,
            lineJoinStyle: 0,
          },
          borders: [
            {
              _class: "border",
              isEnabled: true,
              fillType: 0,
              color: {
                _class: "color",
                alpha: 1,
                blue: 0.592,
                green: 0.592,
                red: 0.592,
              },
              contextSettings: {
                _class: "graphicsContextSettings",
                blendMode: 0,
                opacity: 1,
              },
              gradient: {
                _class: "gradient",
                elipseLength: 0,
                from: "{0.5, 0}",
                gradientType: 0,
                to: "{0.5, 1}",
                stops: [
                  {
                    _class: "gradientStop",
                    position: 0,
                    color: {
                      _class: "color",
                      alpha: 1,
                      blue: 1,
                      green: 1,
                      red: 1,
                    },
                  },
                  {
                    _class: "gradientStop",
                    position: 1,
                    color: {
                      _class: "color",
                      alpha: 1,
                      blue: 0,
                      green: 0,
                      red: 0,
                    },
                  },
                ],
              },
              position: 1,
              thickness: 1,
            },
          ],
          colorControls: {
            _class: "colorControls",
            isEnabled: false,
            brightness: 0,
            contrast: 1,
            hue: 0,
            saturation: 1,
          },
          contextSettings: {
            _class: "graphicsContextSettings",
            blendMode: 0,
            opacity: 1,
          },
          fills: [
            {
              _class: "fill",
              isEnabled: true,
              fillType: 0,
              color: {
                _class: "color",
                alpha: 1,
                blue: 0.847,
                green: 0.847,
                red: 0.847,
              },
              contextSettings: {
                _class: "graphicsContextSettings",
                blendMode: 0,
                opacity: 1,
              },
              gradient: {
                _class: "gradient",
                elipseLength: 0,
                from: "{0.5, 0}",
                gradientType: 0,
                to: "{0.5, 1}",
                stops: [
                  {
                    _class: "gradientStop",
                    position: 0,
                    color: {
                      _class: "color",
                      alpha: 1,
                      blue: 1,
                      green: 1,
                      red: 1,
                    },
                  },
                  {
                    _class: "gradientStop",
                    position: 1,
                    color: {
                      _class: "color",
                      alpha: 1,
                      blue: 0,
                      green: 0,
                      red: 0,
                    },
                  },
                ],
              },
              noiseIndex: 0,
              noiseIntensity: 0,
              patternFillType: 1,
              patternTileScale: 1,
            },
          ],
          innerShadows: [],
          shadows: [],
        },
        edited: false,
        isClosed: true,
        pointRadiusBehaviour: 1,
        points: [
          {
            _class: "curvePoint",
            cornerRadius: 0,
            curveFrom: "{0, 0}",
            curveMode: 1,
            curveTo: "{0, 0}",
            hasCurveFrom: false,
            hasCurveTo: false,
            point: "{0, 0}",
          },
          {
            _class: "curvePoint",
            cornerRadius: 0,
            curveFrom: "{1, 0}",
            curveMode: 1,
            curveTo: "{1, 0}",
            hasCurveFrom: false,
            hasCurveTo: false,
            point: "{1, 0}",
          },
          {
            _class: "curvePoint",
            cornerRadius: 0,
            curveFrom: "{1, 1}",
            curveMode: 1,
            curveTo: "{1, 1}",
            hasCurveFrom: false,
            hasCurveTo: false,
            point: "{1, 1}",
          },
          {
            _class: "curvePoint",
            cornerRadius: 0,
            curveFrom: "{0, 1}",
            curveMode: 1,
            curveTo: "{0, 1}",
            hasCurveFrom: false,
            hasCurveTo: false,
            point: "{0, 1}",
          },
        ],
        fixedRadius: 0,
        needsConvertionToNewRoundCorners: false,
        hasConvertedToNewRoundCorners: true,
      },
    ],
    includeInCloudUpload: true,
    horizontalRulerData: { _class: "rulerData", base: 0, guides: [] },
    verticalRulerData: { _class: "rulerData", base: 0, guides: [] },
  },
  document: {
    _class: "document",
    do_objectID: "8B84C1BB-ADEF-4766-9AD4-F91CE2485378",
    agreedToFontEmbedding: false,
    autoEmbedFonts: false,
    colorSpace: 0,
    currentPageIndex: 0,
    assets: {
      _class: "assetCollection",
      do_objectID: "21BD5B6A-507E-494C-9BCF-CBC641C3BCE9",
      images: [],
      colorAssets: [],
      exportPresets: [],
      gradientAssets: [],
      imageCollection: { _class: "imageCollection", images: {} },
      colors: [],
      gradients: [],
    },
    fontReferences: [],
    foreignLayerStyles: [],
    foreignSwatches: [],
    foreignSymbols: [],
    foreignTextStyles: [],
    layerStyles: { _class: "sharedStyleContainer", objects: [] },
    layerSymbols: { _class: "symbolContainer", objects: [] },
    layerTextStyles: { _class: "sharedTextStyleContainer", objects: [] },
    pages: [
      {
        _class: "MSJSONFileReference",
        _ref_class: "MSImmutablePage",
        _ref: "pages/A869BA2A-E632-4C2D-924E-7883848BB266",
      },
    ],
    sharedSwatches: { _class: "swatchContainer", objects: [] },
  },
  meta: {
    commit: "d06f2f7bf433bc948c6f867ddfb87013f4871eb3",
    pagesAndArtboards: {
      "A869BA2A-E632-4C2D-924E-7883848BB266": {
        name: "Page 1",
        artboards: {},
      },
    },
    version: 130,
    fonts: [],
    compatibilityVersion: 99,
    app: SketchType.FileFormat.default.BundleId.PublicRelease,
    autosaved: 0,
    variant: "NONAPPSTORE",
    created: {
      commit: "d06f2f7bf433bc948c6f867ddfb87013f4871eb3",
      appVersion: "66.1",
      build: 97080,
      app: SketchType.FileFormat.default.BundleId.PublicRelease,
      compatibilityVersion: 99,
      version: 130,
      variant: "NONAPPSTORE",
    },
    saveHistory: ["NONAPPSTORE.97080"],
    appVersion: "66.1",
    build: 97080,
  },
};

export default INIT_DATA;
