import * as path from "path";
import { JSONPack, Page, Layer } from "../../src";

const symbolJSONs = [
  {
    _class: "symbolMaster",
    frame: {
      _class: "rect",
      constrainProportions: false,
      height: 21,
      width: 800,
      x: 0,
      y: 0,
    },
    allowsOverrides: true,
    backgroundColor: {
      _class: "color",
      red: 1,
      green: 1,
      blue: 1,
      alpha: 1,
    },
    booleanOperation: -1,
    changeIdentifier: 0,
    do_objectID: "9F0C4E24-6822-411C-BFB7-49703C9B8BAB",
    symbolID: "A56A226B-DB9D-4712-A932-6C48E7F3E9F1",
    exportOptions: {
      _class: "exportOptions",
      includedLayerIds: [],
      layerOptions: 0,
      shouldTrim: false,
      exportFormats: [],
    },
    hasClickThrough: true,
    includeInCloudUpload: true,
    hasBackgroundColor: false,
    includeBackgroundColorInExport: true,
    resizesContent: false,
    includeBackgroundColorInInstance: false,
    nameIsFixed: false,
    horizontalRulerData: { _class: "rulerData", base: 0, guides: [] },
    verticalRulerData: { _class: "rulerData", base: 0, guides: [] },
    resizingConstraint: 1,
    resizingType: 1,
    groupLayout: { _class: "MSImmutableFreeformGroupLayout" },
    isFixedToViewport: false,
    sharedStyleID: "",
    isFlippedHorizontal: false,
    isFlippedVertical: false,
    isLocked: false,
    isFlowHome: false,
    name: "",
    rotation: 0,
    layerListExpandedType: 0,
    overrideProperties: [
      {
        _class: "MSImmutableOverrideProperty",
        canOverride: true,
        overrideName: "C3776604-4754-4C97-AB43-7BD0E81C99F2_stringValue",
      },
    ],
    layers: [
      {
        _class: "group",
        do_objectID: "32F2EEC5-22DA-41D1-B6E4-EAD25DB555E3",
        booleanOperation: -1,
        isFixedToViewport: false,
        isFlippedHorizontal: false,
        isFlippedVertical: false,
        isVisible: true,
        isLocked: false,
        layerListExpandedType: 0,
        name: "编组",
        nameIsFixed: false,
        resizingConstraint: 63,
        resizingType: 0,
        rotation: 0,
        shouldBreakMaskChain: false,
        exportOptions: {
          _class: "exportOptions",
          includedLayerIds: [],
          layerOptions: 0,
          shouldTrim: false,
          exportFormats: [],
        },
        frame: {
          _class: "rect",
          constrainProportions: false,
          height: 21,
          width: 800,
          x: 0,
          y: 0,
        },
        clippingMaskMode: 0,
        hasClippingMask: false,
        style: {
          _class: "style",
          do_objectID: "94DC1F0F-CE6D-4A02-A5AD-658CDDAF1095",
          endMarkerType: 0,
          miterLimit: 10,
          startMarkerType: 0,
          windingRule: 1,
          borderOptions: {
            _class: "borderOptions",
            isEnabled: true,
            dashPattern: [],
            lineCapStyle: 0,
            lineJoinStyle: 0,
          },
          colorControls: {
            _class: "colorControls",
            isEnabled: false,
            brightness: 0,
            contrast: 1,
            hue: 0,
            saturation: 1,
          },
          fills: [],
          borders: [],
          shadows: [],
          innerShadows: [],
          contextSettings: {
            _class: "graphicsContextSettings",
            blendMode: 0,
            opacity: 1,
          },
        },
        hasClickThrough: false,
        groupLayout: { _class: "MSImmutableFreeformGroupLayout" },
        layers: [
          {
            _class: "text",
            do_objectID: "C3776604-4754-4C97-AB43-7BD0E81C99F2",
            booleanOperation: -1,
            isFixedToViewport: false,
            isFlippedHorizontal: false,
            isFlippedVertical: false,
            isLocked: false,
            isVisible: true,
            name: "文本",
            nameIsFixed: false,
            layerListExpandedType: 0,
            resizingConstraint: 63,
            resizingType: 0,
            rotation: 0,
            shouldBreakMaskChain: false,
            exportOptions: {
              _class: "exportOptions",
              includedLayerIds: [],
              layerOptions: 0,
              shouldTrim: false,
              exportFormats: [],
            },
            frame: {
              _class: "rect",
              constrainProportions: false,
              height: 21,
              width: 179.125,
              x: 0,
              y: 0,
            },
            clippingMaskMode: 0,
            hasClippingMask: false,
            style: {
              _class: "style",
              do_objectID: "861858B9-6A61-4EFD-929A-910AE00BFD93",
              endMarkerType: 0,
              miterLimit: 10,
              startMarkerType: 0,
              windingRule: 1,
              borderOptions: {
                _class: "borderOptions",
                isEnabled: true,
                dashPattern: [],
                lineCapStyle: 0,
                lineJoinStyle: 0,
              },
              colorControls: {
                _class: "colorControls",
                isEnabled: false,
                brightness: 0,
                contrast: 1,
                hue: 0,
                saturation: 1,
              },
              fills: [],
              borders: [],
              shadows: [],
              innerShadows: [],
              contextSettings: {
                _class: "graphicsContextSettings",
                blendMode: 0,
                opacity: 1,
              },
            },
            attributedString: {
              _class: "attributedString",
              string: "这是示例一：带 HiTuSymbol",
              attributes: [
                {
                  _class: "stringAttribute",
                  location: 0,
                  length: 18,
                  attributes: {
                    underlineStyle: 0,
                    MSAttributedStringTextTransformAttribute: 0,
                    paragraphStyle: {
                      _class: "paragraphStyle",
                      maximumLineHeight: 21,
                      minimumLineHeight: 21,
                    },
                    kerning: 0,
                    strikethroughStyle: 0,
                    MSAttributedStringFontAttribute: {
                      _class: "fontDescriptor",
                      attributes: { name: "PingFangSC-Regular", size: 14 },
                    },
                    MSAttributedStringColorAttribute: {
                      _class: "color",
                      red: 0.5725490196078431,
                      green: 0.4392156862745098,
                      blue: 0.792156862745098,
                      alpha: 1,
                    },
                  },
                },
              ],
            },
            automaticallyDrawOnUnderlyingPath: false,
            dontSynchroniseWithSymbol: false,
            lineSpacingBehaviour: 2,
            textBehaviour: 0,
            glyphBounds: "",
          },
        ],
        userInfo: null,
      },
    ],
    isVisible: true,
  },
  {
    _class: "symbolMaster",
    frame: {
      _class: "rect",
      constrainProportions: false,
      height: 21,
      width: 800,
      x: 0,
      y: 21,
    },
    allowsOverrides: true,
    backgroundColor: { _class: "color", red: 1, green: 1, blue: 1, alpha: 1 },
    booleanOperation: -1,
    changeIdentifier: 0,
    do_objectID: "27E81847-351F-4E58-AB46-F0C3BBEFAA19",
    symbolID: "D52D4C7E-EAA1-4E07-8BA2-454BA780B928",
    exportOptions: {
      _class: "exportOptions",
      includedLayerIds: [],
      layerOptions: 0,
      shouldTrim: false,
      exportFormats: [],
    },
    hasClickThrough: true,
    includeInCloudUpload: true,
    hasBackgroundColor: false,
    includeBackgroundColorInExport: true,
    resizesContent: false,
    includeBackgroundColorInInstance: false,
    nameIsFixed: false,
    horizontalRulerData: { _class: "rulerData", base: 0, guides: [] },
    verticalRulerData: { _class: "rulerData", base: 0, guides: [] },
    resizingConstraint: 1,
    resizingType: 1,
    groupLayout: { _class: "MSImmutableFreeformGroupLayout" },
    isFixedToViewport: false,
    sharedStyleID: "",
    isFlippedHorizontal: false,
    isFlippedVertical: false,
    isLocked: false,
    isFlowHome: false,
    name: "",
    rotation: 0,
    layerListExpandedType: 0,
    overrideProperties: [
      {
        _class: "MSImmutableOverrideProperty",
        canOverride: true,
        overrideName: "CBEBDCA6-8C65-41CE-A4AD-C238C18D960E_stringValue",
      },
    ],
    layers: [
      {
        _class: "group",
        do_objectID: "569F620A-02AC-498A-BFC0-EBE227D7D4C4",
        booleanOperation: -1,
        isFixedToViewport: false,
        isFlippedHorizontal: false,
        isFlippedVertical: false,
        isVisible: true,
        isLocked: false,
        layerListExpandedType: 0,
        name: "编组",
        nameIsFixed: false,
        resizingConstraint: 63,
        resizingType: 0,
        rotation: 0,
        shouldBreakMaskChain: false,
        exportOptions: {
          _class: "exportOptions",
          includedLayerIds: [],
          layerOptions: 0,
          shouldTrim: false,
          exportFormats: [],
        },
        frame: {
          _class: "rect",
          constrainProportions: false,
          height: 21,
          width: 800,
          x: 0,
          y: 0,
        },
        clippingMaskMode: 0,
        hasClippingMask: false,
        style: {
          _class: "style",
          do_objectID: "E7593B33-1954-4064-8EF6-EBD00CD80F70",
          endMarkerType: 0,
          miterLimit: 10,
          startMarkerType: 0,
          windingRule: 1,
          borderOptions: {
            _class: "borderOptions",
            isEnabled: true,
            dashPattern: [],
            lineCapStyle: 0,
            lineJoinStyle: 0,
          },
          colorControls: {
            _class: "colorControls",
            isEnabled: false,
            brightness: 0,
            contrast: 1,
            hue: 0,
            saturation: 1,
          },
          fills: [],
          borders: [],
          shadows: [],
          innerShadows: [],
          contextSettings: {
            _class: "graphicsContextSettings",
            blendMode: 0,
            opacity: 1,
          },
        },
        hasClickThrough: false,
        groupLayout: { _class: "MSImmutableFreeformGroupLayout" },
        layers: [
          {
            _class: "text",
            do_objectID: "CBEBDCA6-8C65-41CE-A4AD-C238C18D960E",
            booleanOperation: -1,
            isFixedToViewport: false,
            isFlippedHorizontal: false,
            isFlippedVertical: false,
            isLocked: false,
            isVisible: true,
            name: "文本",
            nameIsFixed: false,
            layerListExpandedType: 0,
            resizingConstraint: 63,
            resizingType: 0,
            rotation: 0,
            shouldBreakMaskChain: false,
            exportOptions: {
              _class: "exportOptions",
              includedLayerIds: [],
              layerOptions: 0,
              shouldTrim: false,
              exportFormats: [],
            },
            frame: {
              _class: "rect",
              constrainProportions: false,
              height: 21,
              width: 179.125,
              x: 0,
              y: 0,
            },
            clippingMaskMode: 0,
            hasClippingMask: false,
            style: {
              _class: "style",
              do_objectID: "9266C087-4CD8-4056-9961-0E4A60CE2C8A",
              endMarkerType: 0,
              miterLimit: 10,
              startMarkerType: 0,
              windingRule: 1,
              borderOptions: {
                _class: "borderOptions",
                isEnabled: true,
                dashPattern: [],
                lineCapStyle: 0,
                lineJoinStyle: 0,
              },
              colorControls: {
                _class: "colorControls",
                isEnabled: false,
                brightness: 0,
                contrast: 1,
                hue: 0,
                saturation: 1,
              },
              fills: [],
              borders: [],
              shadows: [],
              innerShadows: [],
              contextSettings: {
                _class: "graphicsContextSettings",
                blendMode: 0,
                opacity: 1,
              },
            },
            attributedString: {
              _class: "attributedString",
              string: "这是示例二：带 HiTuSymbol",
              attributes: [
                {
                  _class: "stringAttribute",
                  location: 0,
                  length: 18,
                  attributes: {
                    underlineStyle: 0,
                    MSAttributedStringTextTransformAttribute: 0,
                    paragraphStyle: {
                      _class: "paragraphStyle",
                      maximumLineHeight: 21,
                      minimumLineHeight: 21,
                    },
                    kerning: 0,
                    strikethroughStyle: 0,
                    MSAttributedStringFontAttribute: {
                      _class: "fontDescriptor",
                      attributes: { name: "PingFangSC-Regular", size: 14 },
                    },
                    MSAttributedStringColorAttribute: {
                      _class: "color",
                      red: 0.5725490196078431,
                      green: 0.4392156862745098,
                      blue: 0.792156862745098,
                      alpha: 1,
                    },
                  },
                },
              ],
            },
            automaticallyDrawOnUnderlyingPath: false,
            dontSynchroniseWithSymbol: false,
            lineSpacingBehaviour: 2,
            textBehaviour: 0,
            glyphBounds: "",
          },
        ],
        userInfo: null,
      },
    ],
    isVisible: true,
  },
];

const targetPath = "temp/symbol/symboljson";
const packPath = path.join(targetPath, "pack");
const filePath = path.join(targetPath, "file.sketch");

(async () => {
  try {
    const newLayers = symbolJSONs.map((json, index) => {
      const data = { ...json };
      data.name = `asset-${index}`;

      return new Layer({
        class: "SymbolMaster",
        data,
      });
    });

    const newPage = new Page({
      name: "Assets",
      layers: newLayers.map((layer) => layer.toSketchJSON()),
    } as any);
    const newPack = new JSONPack({ pages: [newPage] } as any);

    await newPack.write(packPath);
    await newPack.zip(filePath);
  } catch (error) {
    throw error;
  }
})();
